import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Lenovo' at '26.10.2014 12:54' with Gradle 2.1
 *
 * @author Lenovo, @date 26.10.2014 12:54
 */
public class TicTacToeTest {
	@Test
	public void TestX()
	{
		assertEquals(0, TicTacToe.PlayBoard(2,2));
	}
}
