/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Lenovo' at '26.10.2014 12:54' with Gradle 2.1
 *
 * @author Lenovo, @date 26.10.2014 12:54
 */
public class TicTacToe {
    public boolean someLibraryMethod() {
        return true;
    }
}